# Generated by Django 3.0.5 on 2020-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.CharField(default='default article name', max_length=1024, verbose_name='Article name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_articles', verbose_name='Image'),
        ),
    ]
